version: "3.6"
services:
  database:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
  api:
    build: .
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/tasks"
  frontend:
    build: ../frontend
    restart: always
    ports:
      - "3000:3000"
volumes:
  db_data:
  